# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-15 23:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicants',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
