# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-17 21:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_name',
            field=models.CharField(default='', max_length=250),
        ),
    ]
