# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-18 09:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20160418_0747'),
        ('backend', '0002_project_project_name'),
    ]

    operations = [
    ]
