# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-18 10:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='photo',
            field=models.URLField(default='img/user_default.png'),
        ),
        migrations.AlterField(
            model_name='project',
            name='skills',
            field=models.CharField(default='', max_length=250),
        ),
    ]
